repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
        files: pyproject.toml
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'  # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
